# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "archlinux-x86_64"

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.ssh.forward_x11 = true

  config.vm.provision "shell", path: "scripts/update.sh"
  config.vm.provision "shell", path: "scripts/devtools.sh"
  config.vm.provision "shell", path: "scripts/multilib.sh"
  config.vm.provision "shell", path: "scripts/nettools.sh"
  config.vm.provision "shell", path: "scripts/x.sh"
  config.vm.provision "shell", path: "scripts/archassault.sh"
  config.vm.provision "shell", path: "scripts/archassault-tools.sh"
  config.vm.provision "shell", path: "scripts/metasploit.sh"
  config.vm.provision "shell", path: "scripts/harden.sh"

end

