# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "kali-106-amd64"

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.ssh.forward_x11 = true

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "65"]
    vb.name = "Kali"
    #vb.gui = true
  end

  config.ssh.forward_x11 = true

  config.vm.provision "shell", path: "scripts/updatepackages.sh"
  config.vm.provision "shell", path: "scripts/metasploit.sh"

end

